# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/clx/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/clx/labels

Python:
  - 'python/**'
  - 'notebooks/**'
  
integration:
  - 'siem_integrations'

gpuCI:
  - 'ci/**'

conda:
  - 'conda/**'
