version: '3'
services:
  #JupyterLab will be available at port 9888
  clx:
    build: .
    ports:
      - "9888:8888"
      - "8787:8787"
      - "8686:8686"
    stdin_open: true
    tty: true
    runtime: nvidia
  #Zookeeper will be available at `zookeeper:2181`
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  #Kafka will be available at `kafka:9092`
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
