# Copyright (c) 2019, NVIDIA CORPORATION.

# Usage:
#   conda build -c conda-forge -c defaults .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set cuda_version=environ.get('CUDA_REL', '0') %}

package:
  name: clx
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - python
    - cython>=0.29,<0.30
    - libclx={{ version }}
  run:
    - python
    - mkl
    - scikit-learn>=0.21
    - libclx={{ version }}
    - cugraph {{ minor_version }}.*
    - cuml {{ minor_version }}.*
    - dask-cudf {{ minor_version }}.*
    - pytorch=1.5.*
    - torchvision

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: clx library
