ARG version=cuda9.2-runtime-ubuntu16.04

FROM rapidsai/rapidsai:${version}

ADD . /rapidscyber/

ADD ./ci/integration_tests/run_integration_test.py /rapidscyber/run_integration_test.py

SHELL ["/bin/bash", "-c"]
RUN source activate rapids \
    && cd /rapidscyber \
    && python setup.py install

WORKDIR /rapidscyber
CMD source activate rapids && python run_integration_test.py