ARG version=cuda10.0-runtime-ubuntu18.04

FROM rapidsai/rapidsai:${version}

ADD . /clx/

ADD ./ci/integration_tests/run_integration_test.py /clx/run_integration_test.py

SHELL ["/bin/bash", "-c"]
RUN source activate rapids \
    && cd /clx \
    && python setup.py install

WORKDIR /clx
CMD source activate rapids && python run_integration_test.py